### ISSUE TITLE
Failed to run your code due to missing file （R_objects/se.Colon)

### ISSUE THREAD

**Issue by pangkun97** [ludvigla/healing_intestine_analysis#2]
Hello，I want to run this script but fail.

[Digital_unrolling.Rmd](https://github.com/ludvigla/healing_intestine_analysis/blob/main/doc/Digital_unrolling.Rmd)

Can you provide the missing data file again？

Thank you！

**Comment by ludvigla** [comment]
I have added instructions for how to create the se.Colon object using the files already available under data/. The instructions can now be found in the "Digital_unrolling.Rmd" file.

/Ludvig
